version: '2'
services:
  mc-server:
    network_mode: host
    restart: no
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - minecraft-data:/data
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
      - "25575:25575/udp"
      - "25575:25575/tcp"
  scp-server:
    network_mode: host
    restart: always
    build: ./scp-server
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - minecraft-data:/serverfiles
    ports:
      - "22:22/udp"
      - "22:22/tcp"
volumes:
  minecraft-data:
